services:
  db:
    image: postgres:15-alpine
    container_name: pipeline_postgres_db
    environment:
      POSTGRES_DB: transaction_pipeline
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecurepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    container_name: pipeline_redis_broker
    ports:
      - "6379:6379"
    restart: always

  web_api:
    build: .
    container_name: pipeline_fastapi_server
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - shared_tmp:/tmp                 
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:supersecurepassword@db:5432/transaction_pipeline
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
      - redis
    restart: always

  celery_worker:
    build: .
    container_name: pipeline_celery_worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/code
      - shared_tmp:/tmp                 
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:supersecurepassword@db:5432/transaction_pipeline
      - REDIS_URL=redis://redis:6379/0
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis
      - db
    restart: always

volumes:
  postgres_data:
  shared_tmp:                          